### PR TITLE
Standardise on 'filename' (not 'file name') in manual pages

### PR DESCRIPTION
**Pull request by larryhynes**
- magrep.1
- mcom.1
- mexport.1
- mflag.1
- mhdr.1
- minc.1
- mmsg.7
- mscan.1
- mseq.1
- mshow.1
- msort.1
- mthread.1

### CODE REVIEW

**Comment by chneukirchen** [comment]
+1, can you rebase please?

**Comment by larryhynes** [comment]
That may be tricky, because

1. I have no idea what I'm doing
2. I did the merge here on github to get around a conflict in (I think) `mhdr.1`, and now my local version is behind this version and Santa Claus is sad.
3. Did I mention I have no idea what I'm doing?

**Comment by chneukirchen** [comment]
Github PR are just branches, you can `push -f` anything there.

**Comment by chneukirchen** [comment]
But I guess I can run `sed -i` myself too. ;)

**Comment by larryhynes** [comment]
`-f` - of course! Thanks 😄

**Pull request closed without merging**
