### PR TITLE
mcom.1: update wording

### PR DESCRIPTION
**Pull request by larryhynes**
I took a scalpel to this, but I don't think you would miss anything that was cut, really.

- clean up SYNOPSIS
- move mrep up
- edit DESCRIPTION
- mail -> message, throughout

### CODE REVIEW

**Comment by chneukirchen** [comment]
I agree the NAME was cluttered, but else apropos fails to find "forward" and "bounce" no?

**Comment by larryhynes** [comment]
How about the very minimal:

```
diff --git a/man/mcom.1 b/man/mcom.1
index 633b0bd..d4b9267 100644
--- a/man/mcom.1
+++ b/man/mcom.1
@@ -6,7 +6,7 @@
 .Nm mfwd ,
 .Nm mbnc ,
 .Nm mrep
-.Nd compose and send messages
+.Nd compose, reply, forward, bounce, send messages
 .Sh SYNOPSIS
 .Nm mcom
 .Op Ar recipients\ ...
```

**Comment by chneukirchen** [comment]
:+1:

**Comment by larryhynes** [comment]
Done.

**Pull request closed without merging**
